### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by HyogoMoura** [HyogoMoura/GCMS-Diogo-Moura#2]
Hello @ramidedantas !
After accepting the collaboration invitation please update the [README](https://github.com/hyogomoura/GCMS-Diogo-Moura/edit/main/README.md) file,  adding your name at collabs section.

**Comment by ramidedantas** [comment]
@HyogoMoura please fix the README format (bullets, titles, etc.)

**Comment by HyogoMoura** [comment]
@ramidedantas Format fixed!
* Missing bullets were added. 
* Title was adjusted according the original content.

**Comment by ramidedantas** [comment]
@HyogoMoura name added; issue can be closed.
